name: "Pull Request Checks"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

jobs:
  test-and-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --group format --group test --group docs --group external-integration
  
      - name: Get branch name
        id: branch-name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Run tests
        run: uv run pytest

      - name: Install nbmake
        run: uv pip install nbmake
      - name: Test notebooks
        run: uv run pytest --nbmake docs/source/examples/*ipynb

      - name: Update version
        run: |
          uv run semantic-release version \
            --prerelease \
            --no-commit \
            --no-tag \
            --skip-build \
            --build-metadata ${{ steps.branch-name.outputs.branch }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update version [skip ci]"
          file_pattern: "pyprobe/_version.py"